services:
  - type: web
    name: karisik
    env: node
    region: frankfurt
    buildCommand: npm install && npx playwright install chromium
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
