services:
  - type: web
    name: karisik
    env: node
    region: frankfurt
    buildCommand: npm install && PLAYWRIGHT_BROWSERS_PATH=./.playwright npx playwright install chromium
    startCommand: PLAYWRIGHT_BROWSERS_PATH=./.playwright npm start
    envVars:
      - key: NODE_ENV
        value: production
